### ISSUE TITLE
Replace package meteor's aldeed:simple-schema with NPM 'simpl-schema'

### ISSUE THREAD

**Issue by sethjgore** [rhettlivingston/meteor-simple-schema-mixin#4]
SimpleSchema was recently repackaged as a NPM package and it's the main repo now. Some issues I'm facing is because this package is referring to the meteor package. I've tried all of the available fixes and it doesn't work because these fix refer to the NPM SS not Meteor SS. 

I can do a pull request if you would like that. 

```
Invalid definition for pick field.
W20170406-19:32:19.482(-4)? (STDERR)     at packages/aldeed_simple-schema.js:1429:13
W20170406-19:32:19.482(-4)? (STDERR)     at Function._.each._.forEach (packages/underscore.js:147:22)
```

**Comment by rhettlivingston** [comment]
I am no longer actively developing but would be happy to incorporate a pull request.

**Comment by sethjgore** [comment]
Great. I'll get to it when I can. Any particular reason why you aren't actively developing this? Not using meteor as a platform anymore?

**Comment by sethjgore** [comment]
I've updated and made a pull request.  See [here](https://github.com/rhettlivingston/meteor-simple-schema-mixin/pull/5)

**Comment by rhettlivingston** [comment]
Honestly, I dropped all development activities. After a 20 year career, I took 10 years off development and then couldn't figure out how to monetize my expertise in the vastly different development world I tried to return to. Time ran out on the experiment when the need to have a paying job struck.

**Comment by sethjgore** [comment]
Gotcha. How's the job paying now? Hope it's a great fit. I'm a similar stint, ha.
